export default [
  'EDITORIAL MATTERS',
  'BUSINESS PROPOSITIONS',
  'ADVERTISING INQUIRIES',
  'LEGAL ISSUES',
  'EMPLOYMENT INQUIRIES',
  'EMERGENCIES',
  'FOR QUESTIONS OR COMMENTS ABOUT OUR WEBISODES OR VIDEOS',
  'FOR GENERAL INQUIRIES OR COMMENTS',
];
